name: Convert Excel to JSON and Push to GitHub

on:
  schedule:
    - cron: '0 0 * * *'  # Jalankan setiap hari pada tengah malam
  push:
    branches:
      - main  # Jalankan juga saat ada push ke branch main

jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GITHUB_TOKEN bawaan

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl requests

    - name: Run Python script
      run: |
        python convert_excel_to_json.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GITHUB_TOKEN bawaan
      run: |
        git config --global user.email "nurdiyanto7@gmail.com"
        git config --global user.name "boneyanto"
        git add data-pegawai.json data-pegawai.xlsx
        git commit -m "Update data pegawai dan dosen"
        git push https://$GITHUB_TOKEN@github.com/boneyanto/datapegawai.git main